# Generated by Django 3.2.16 on 2022-12-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetings',
            name='number_greetings',
            field=models.IntegerField(default=0),
        ),
    ]
